### ISSUE TITLE
The generated image is quite different from the reference image

### ISSUE THREAD

**Issue by 1273545169** [wty-ustc/HairCLIP#9]
I tested the effect and found that the hair style of the generated image is quite different from that of the reference image. Here is my test script. The reference image is selected from CelebAMask-HQ dataset. Is there a problem in my test process？

`python scripts/inference.py \
--exp_dir=../outputs/0321/ \
--checkpoint_path=../pretrained_models/hairclip.pt \
--latents_test_path=../pretrained_models/test_faces.pt \
--editing_type=both \
--input_type=image_image \
--color_ref_img_test_path=../input/16 \
--hairstyle_ref_img_test_path=../input/16 --num_of_ref_img 1`

 
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/33993637/159227090-7474fd15-c089-425c-bf48-d636902ca465.png">

**Comment by wty-ustc** [comment]
As stated in the limitations of our paper, since our hairstyle transfer embedding is provided by the image encoder of CLIP, it may not be good enough for characterizing the fine-grained structure of hairstyles, so the results may sometimes be unsatisfactory. You can try other images, or train HairCLIP specifically for hairstyle transfer, or add optimization strategies.

**Comment by 1273545169** [comment]
Thank you so much
